//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS20
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Условие.
    /// </summary>
    // *** Start programmer edit section *** (Условие CustomAttributes)

    // *** End programmer edit section *** (Условие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УсловиеE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("УсловиеL", new string[] {
            "Наименование"})]
    public class Условие : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.ISS20.ВидПоддержки fВидПоддержки;
        
        // *** Start programmer edit section *** (Условие CustomMembers)

        // *** End programmer edit section *** (Условие CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Условие.Наименование CustomAttributes)

        // *** End programmer edit section *** (Условие.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Условие.Наименование Get start)

                // *** End programmer edit section *** (Условие.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Условие.Наименование Get end)

                // *** End programmer edit section *** (Условие.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.Наименование Set start)

                // *** End programmer edit section *** (Условие.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Условие.Наименование Set end)

                // *** End programmer edit section *** (Условие.Наименование Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ISS20.ВидПоддержки.
        /// </summary>
        // *** Start programmer edit section *** (Условие.ВидПоддержки CustomAttributes)

        // *** End programmer edit section *** (Условие.ВидПоддержки CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.ISS20.ВидПоддержки ВидПоддержки
        {
            get
            {
                // *** Start programmer edit section *** (Условие.ВидПоддержки Get start)

                // *** End programmer edit section *** (Условие.ВидПоддержки Get start)
                IIS.ISS20.ВидПоддержки result = this.fВидПоддержки;
                // *** Start programmer edit section *** (Условие.ВидПоддержки Get end)

                // *** End programmer edit section *** (Условие.ВидПоддержки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.ВидПоддержки Set start)

                // *** End programmer edit section *** (Условие.ВидПоддержки Set start)
                this.fВидПоддержки = value;
                // *** Start programmer edit section *** (Условие.ВидПоддержки Set end)

                // *** End programmer edit section *** (Условие.ВидПоддержки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УсловиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеE", typeof(IIS.ISS20.Условие));
                }
            }
            
            /// <summary>
            /// "УсловиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеL", typeof(IIS.ISS20.Условие));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Условие.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУсловие CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУсловие CustomAttributes)
    public class DetailArrayOfУсловие : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ISS20.DetailArrayOfУсловие members)

        // *** End programmer edit section *** (IIS.ISS20.DetailArrayOfУсловие members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Условие by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Условие.
        /// </summary>
        public DetailArrayOfУсловие(IIS.ISS20.ВидПоддержки fВидПоддержки) : 
                base(typeof(Условие), ((ICSSoft.STORMNET.DataObject)(fВидПоддержки)))
        {
        }
        
        public IIS.ISS20.Условие this[int index]
        {
            get
            {
                return ((IIS.ISS20.Условие)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ISS20.Условие dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
